#!/usr/bin/env python3
"""Phase-1 forward-equivalence gate: run the native NDVM runtime on each Phase-0 program and compare
its forward output to the PyTorch DMCI oracle reference (results/oracle_refs.json, generated by
oracle_refs.py on HPC). NDVM is fed the IDENTICAL source string and bindings the oracle used.

Tolerances: scalar/transcendental/recursive programs are expected to match tightly (float32 of the
same scalar ops); the matrix rollout (Kalman) allows a looser relative tolerance because LU-based
float32 linear algebra differs from torch/LAPACK in reduction order (documented parity risk).

    python3 compare_equivalence.py [--ndvm-run PATH] [--refs results/oracle_refs.json]
"""
from __future__ import annotations
import argparse, json, math, subprocess, tempfile, os, sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
DEFAULT_RUN = HERE.parents[0] / "build" / "ndvm_run"

# per-program (abs, rel) tolerance; default 1e-5/1e-5 for unlisted programs.
TOL = {
    "logistic_map_loop":(1e-4, 1e-4),   # 16 chaotic float32 steps amplify low-bit differences
    "kalman2d_T80":     (1e-2, 2e-3),   # LU float32 vs LAPACK over an 80-step rollout
    "recursive_define": (1e-4, 1e-4),
}
DEFAULT_TOL = (1e-5, 1e-5)

# per-program (abs, rel) tolerance for gradients (NDVM native backward vs oracle autograd).
GTOL = {
    "logistic_map_loop": (1e-3, 1e-3),
    "kalman2d_T80":      (5.0, 2e-2),   # LU vs LAPACK matrix adjoints over 80 steps; grads ~1e3-1e4
    "logdet_grad":       (1e-3, 1e-3),  # LU inverse vs LAPACK
}
GDEFAULT = (1e-4, 1e-4)


def run_ndvm(run_path, src, scalars, matrix, grad=False):
    """Run ndvm_run; return (result, grads_dict). grads_dict empty unless grad=True."""
    with tempfile.TemporaryDirectory() as d:
        sp = Path(d) / "p.scm"; sp.write_text(src + "\n")
        bp = Path(d) / "p.bind"
        lines = [f"scalar {k} {v!r}" for k, v in scalars.items()]
        if matrix:
            data = " ".join(repr(x) for x in matrix["data"])
            lines.append(f"matrix {matrix['name']} {matrix['rows']} {matrix['cols']} {data}")
        bp.write_text("\n".join(lines) + "\n")
        env = dict(os.environ)
        if grad:
            env["NDVM_GRAD"] = "1"
        out = subprocess.run([str(run_path), str(sp), str(bp)], capture_output=True, text=True, env=env)
        if out.returncode != 0:
            raise RuntimeError(f"ndvm_run failed: {out.stderr.strip()}")
        result, grads = None, {}
        for line in out.stdout.splitlines():
            if line.startswith("result "):
                result = float(line.split()[1])
            elif line.startswith("grad "):
                _, name, val = line.split()
                grads[name] = float(val)
        if result is None:
            raise RuntimeError(f"no result line: {out.stdout!r}")
        return result, grads


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ndvm-run", default=str(DEFAULT_RUN))
    ap.add_argument("--refs", default=str(HERE / "results" / "oracle_refs.json"))
    args = ap.parse_args()

    refs = json.loads(Path(args.refs).read_text())
    print(f"oracle host={refs.get('host')} torch={refs.get('torch')}")
    npass = nfail = 0
    gpass = gfail = 0
    for p in refs["programs"]:
        name = p["name"]
        if "oracle_result" not in p:
            print(f"  [SKIP] {name:18s} oracle error: {p.get('error')}"); continue
        oracle_grads = p.get("grads") or {}
        try:
            got, ggrads = run_ndvm(args.ndvm_run, p["src"], p["scalars"], p.get("matrix"),
                                   grad=bool(oracle_grads))
        except Exception as e:  # noqa: BLE001
            print(f"  [FAIL] {name:18s} ndvm error: {e}"); nfail += 1; continue
        want = p["oracle_result"]
        atol, rtol = TOL.get(name, DEFAULT_TOL)
        if not math.isfinite(want) or not math.isfinite(got):
            ok = (math.isnan(want) and math.isnan(got)) or (got == want)
            print(f"  [{'PASS' if ok else 'FAIL'}] {name:18s} fwd ndvm={got} oracle={want} (non-finite)")
        else:
            diff = abs(got - want)
            ok = diff <= atol + rtol * abs(want)
            print(f"  [{'PASS' if ok else 'FAIL'}] {name:18s} fwd ndvm={got:.9g} oracle={want:.9g} "
                  f"absdiff={diff:.3e}")
        npass += ok; nfail += (not ok)

        # gradient equivalence (NDVM native backward vs oracle autograd)
        gatol, grtol = GTOL.get(name, GDEFAULT)
        for k, gw in oracle_grads.items():
            gn = ggrads.get(k)
            if gn is None:
                print(f"           grad {k}: MISSING from ndvm"); gfail += 1; continue
            gd = abs(gn - gw)
            gok = gd <= gatol + grtol * abs(gw)
            gpass += gok; gfail += (not gok)
            flag = "ok " if gok else "XX "
            print(f"           {flag}d/d{k}: ndvm={gn:.6g} oracle={gw:.6g} absdiff={gd:.3e}")
    print(f"\n=== forward: {npass}/{npass + nfail} match | gradients: {gpass}/{gpass + gfail} match (within tol) ===")
    return 0 if (nfail == 0 and gfail == 0) else 1


if __name__ == "__main__":
    sys.exit(main())
