############################################################
#
# DMCI: Compiling scheme into composable and
#       differentiable neural network representations
#
# emit.py: Emit a standalone, importable ``torch.nn.Module`` from a compiled Scheme program. ``emit_torch_module`` returns...
#
# Luke Sheneman
# Research Computing and Data Services (RCDS)
# Institute for Interdisciplinary Data Sciences (IIDS)
# University of Idaho
# sheneman@uidaho.edu
#
############################################################

"""Emit a standalone, importable ``torch.nn.Module`` from a compiled Scheme program.

``emit_torch_module`` returns the source of a self-contained Python file that embeds the
compiled graph and exposes a ``CompiledModel(torch.nn.Module)``: the input names you mark as
``params`` become ``torch.nn.Parameter``s (learnable constants to optimize), and the remaining
declared inputs become ``forward()`` keyword arguments (the data). Dropping the file into an
optimization or search loop is then just a standard PyTorch training loop.

The emitted file depends only on ``neural_compiler`` (for the evaluator) and ``torch``.
"""
from __future__ import annotations

import json

from neural_compiler.graph.builder import ComputeGraph
from neural_compiler.serialize import graph_to_dict

_TEMPLATE = '''"""Auto-generated by nncompile -- do not edit by hand.

Compiled from Scheme source:
    {source}

A differentiable torch.nn.Module. Learnable constants (params): {params_list}.
Data inputs (forward kwargs): {inputs_list}.

Example (recover the params by gradient descent):

    import torch
    from {module_name} import CompiledModel

    model = CompiledModel({init_example})           # initial guesses for the params
    opt = torch.optim.Adam(model.parameters(), lr=0.05)
    for _ in range(2000):
        pred = torch.stack([model({forward_example}) for x_i, y_i in data])  # your data loop
        loss = ((pred - targets) ** 2).mean()
        opt.zero_grad(); loss.backward(); opt.step()
    print({{n: p.item() for n, p in model.params.items()}})
"""
import json

import torch

from neural_compiler.serialize import graph_from_dict
from neural_compiler.evaluator import evaluate, evaluate_batched
from neural_compiler.runtime.tagged_value import make_float, unwrap_number

SOURCE = {source!r}
PARAMS = {params!r}          # learnable input names -> torch.nn.Parameter
INPUTS = {inputs!r}          # data input names -> forward() keyword arguments
USES_TAGGED_VALUES = {uses_tagged!r}

_GRAPH_JSON = {graph_json!r}
_GRAPH = graph_from_dict(json.loads(_GRAPH_JSON))


class CompiledModel(torch.nn.Module):
    """Differentiable module for: {source}

    ``params`` are exposed as a ``torch.nn.ParameterDict`` (so ``model.parameters()`` and
    ``model.params[name]`` work as usual). ``forward`` takes the data inputs as keyword
    arguments and returns a differentiable tensor.
    """

    def __init__(self, **param_init):
        super().__init__()
        self.params = torch.nn.ParameterDict({{
            name: torch.nn.Parameter(torch.as_tensor(float(param_init.get(name, 0.0))))
            for name in PARAMS
        }})

    def forward(self, **inputs):
        missing = [n for n in INPUTS if n not in inputs]
        if missing:
            raise TypeError(f"forward() missing data input(s): {{missing}}")
        if USES_TAGGED_VALUES:
            # heap/list programs run through the tagged evaluator (not batchable).
            feed = {{n: make_float(self.params[n]) for n in PARAMS}}
            feed.update({{n: make_float(torch.as_tensor(inputs[n], dtype=torch.float32))
                         for n in INPUTS}})
            return unwrap_number(evaluate(_GRAPH, feed))
        # arithmetic programs: the batched evaluator keeps the autograd graph and broadcasts,
        # so scalar or (B,) data both work.
        feed = {{n: self.params[n] for n in PARAMS}}
        feed.update({{n: torch.as_tensor(inputs[n], dtype=torch.float32) for n in INPUTS}})
        return evaluate_batched(_GRAPH, feed)


__all__ = ["CompiledModel", "SOURCE", "PARAMS", "INPUTS"]
'''


_JAX_TEMPLATE = '''"""Auto-generated by nncompile -- do not edit by hand.

A JAX module compiled from Scheme source:
    {source}

Learnable constants (params): {params_list}.  Data inputs: {inputs_list}.
JAX is functional: ``apply(params, **data)`` returns a value; differentiate with
``jax.grad``. ``apply`` is a scalar function -- ``jax.vmap`` it over a batch of data.

Example (recover the params by gradient descent):

    import jax, jax.numpy as jnp
    from {module_name} import apply, init_params, INPUTS

    params = init_params({init_example})
    @jax.jit
    def step(params):
        def loss(p):
            pred = jax.vmap(lambda d: apply(p, **d))(data)   # data: pytree of (B,) arrays
            return jnp.mean((pred - targets) ** 2)
        g = jax.grad(loss)(params)
        return {{k: params[k] - 0.05 * g[k] for k in params}}
    for _ in range(2000):
        params = step(params)
"""
import json

import jax
import jax.numpy as jnp

from neural_compiler.serialize import graph_from_dict
from neural_compiler.evaluator.engine_generic import evaluate_generic
from neural_compiler.backend.jax_backend import JaxBackend

SOURCE = {source!r}
PARAMS = {params!r}          # learnable input names (the constants to optimize)
INPUTS = {inputs!r}          # data input names
USES_TAGGED_VALUES = {uses_tagged!r}

_GRAPH_JSON = {graph_json!r}
_GRAPH = graph_from_dict(json.loads(_GRAPH_JSON))
_BACKEND = JaxBackend()


def init_params(**overrides):
    """Return a params pytree (dict) of float32 scalars; override any with a keyword."""
    return {{name: jnp.asarray(float(overrides.get(name, 0.0)), jnp.float32) for name in PARAMS}}


def apply(params, **inputs):
    """Evaluate the program. ``params`` is the learnable-constant pytree; ``inputs`` are the
    data inputs as keyword arguments. Returns a JAX value; fully ``jax.grad``/``jax.vmap``-able
    (control flow must not depend on the differentiated constants)."""
    missing = [n for n in INPUTS if n not in inputs]
    if missing:
        raise TypeError(f"apply() missing data input(s): {{missing}}")
    feed = dict(params)
    feed.update(inputs)
    return evaluate_generic(_GRAPH, feed, _BACKEND, raw_result=True)


__all__ = ["apply", "init_params", "SOURCE", "PARAMS", "INPUTS"]
'''


def emit_jax_module(
    graph: ComputeGraph,
    source: str,
    params: list[str],
    data_inputs: list[str],
    module_name: str = "compiled_model",
) -> str:
    """Return the source of a standalone JAX module (functional ``apply`` + ``init_params``).

    Same param/data-input contract as :func:`emit_torch_module`. JAX evaluation is scalar
    (per call); ``jax.vmap`` ``apply`` over a batch. Heap/list (tagged) programs are not
    supported by the JAX backend.
    """
    if graph.uses_tagged_values:
        raise ValueError("the JAX backend does not support heap/list (tagged) programs; "
                         "use --backend torch, or compile without --dmci")
    declared = list(graph.input_names)
    bad = [p for p in params if p not in declared]
    if bad:
        raise ValueError(f"--params names not declared as inputs of the program: {bad} "
                         f"(declared inputs: {declared})")
    init_example = ", ".join(f"{p}=1.0" for p in params) if params else ""
    return _JAX_TEMPLATE.format(
        source=source, params=params, inputs=data_inputs, uses_tagged=graph.uses_tagged_values,
        graph_json=json.dumps(graph_to_dict(graph)), module_name=module_name,
        params_list=", ".join(params) or "(none)", inputs_list=", ".join(data_inputs) or "(none)",
        init_example=init_example,
    )


def emit_torch_module(
    graph: ComputeGraph,
    source: str,
    params: list[str],
    data_inputs: list[str],
    module_name: str = "compiled_model",
) -> str:
    """Return the source of a standalone ``torch.nn.Module`` file for ``graph``.

    ``params`` and ``data_inputs`` must partition ``graph.input_names``: ``params`` become
    learnable ``nn.Parameter``s and ``data_inputs`` become ``forward()`` keyword arguments.
    """
    declared = list(graph.input_names)
    bad = [p for p in params if p not in declared]
    if bad:
        raise ValueError(f"--params names not declared as inputs of the program: {bad} "
                         f"(declared inputs: {declared})")
    overlap = set(params) & set(data_inputs)
    if overlap:
        raise ValueError(f"names are both params and data inputs: {sorted(overlap)}")

    init_example = ", ".join(f"{p}=1.0" for p in params) if params else ""
    forward_example = ", ".join(f"{n}=x_i" for n in data_inputs) if data_inputs else ""
    return _TEMPLATE.format(
        source=source,
        params=params,
        inputs=data_inputs,
        uses_tagged=graph.uses_tagged_values,
        graph_json=json.dumps(graph_to_dict(graph)),
        module_name=module_name,
        params_list=", ".join(params) or "(none)",
        inputs_list=", ".join(data_inputs) or "(none)",
        init_example=init_example,
        forward_example=forward_example,
    )
